[book]
authors = ["Heliax R&D Team"]
edit-url-template = "https://github.com/anoma/anoma/edit/master/docs/{path}"
git-repository-url = "https://github.com/anoma/anoma"
language = "en"
multilingual = false
site-url = "https://docs.anoma.network/master/"
src = "src"
title = "Anoma - DOCS"

[output.html]
additional-css = ["assets/custom.css"]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]
mathjax-support = true

[output.html.search]
expand = true

[output.linkcheck]

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
